STACK SEGMENT PARA 'STACK'
	DB 64 DUP (' ')
STACK ENDS
DATA SEGMENT PARA 'DATA'
   BALL_X  DW 0AH ; BALL INTIAL X POSITION
   BALL_Y DW 0AH ; BALL INTIAL Y POSITION
   BALL_SIZE DW 04H; BALL SIZE (HOW MANY PIXELS IN HIEGHT AND WIDTH)
DATA ENDS
CODE SEGMENT PARA 'CODE'
	MAIN PROC FAR
	 ASSUME   SS:STACK, DS:DATA, CS:CODE
   MOV AX, DATA         ;Set address of data segment in DS
   MOV DS, AX
	MOV AH,00H; SET VIDEO MODE
	MOV AL,13H; 256 COLOR GRAPHICS
	INT 10H; EXCUTE INTERRUPT
	MOV AH, 06h    ; Scroll up function
    XOR AL, AL     ; Clear entire screen
    XOR CX, CX     ; Upper left corner CH=row, CL=column
    MOV DX, 184FH  ; lower right corner DH=row, DL=column 
    MOV BH, 03h    ; CYAN
	INT 10H
	MOV AH,0CH; WRITE PIXEL
    MOV AL,	0FH;WHITE
	MOV BH,00H; PAGE NUMBER
	MOV CX,BALL_X;SET THE COLOUMN (x)
	MOV DX,BALL_Y;SET THE LINE (Y)
	INT 10H
	CALL DRAW_BALL
	RET
	MAIN ENDP
	DRAW_BALL PROC NEAR
	MOV CX,BALL_X;SET THE INTIAL COLOUMN (x)
	MOV DX,BALL_Y;SET THE INTIAL LINE (Y)
	
	DRAW_BALL_HORIZONTAL:
		MOV AH,0CH; WRITE PIXEL
		MOV AL,	0FH;WHITE
		MOV BH,00H; PAGE NUMBER
		INT 10H
		
		INC CX;COMPARE CX TO THE INTIAL VALUE OF THE POSITION IF IT'S NOT GREATER THAN BALL_SIZE THEN WE ITTERATE ONCE MORE
		MOV AX,CX
		SUB AX,BALL_X
		CMP AX,BALL_SIZE
		JNG DRAW_BALL_HORIZONTAL
		
		MOV CX,BALL_X;
		INC DX; INCREMNT AND COMPARE AS WELL
		MOV AX,DX
		SUB AX,BALL_Y
		CMP AX,BALL_SIZE
		JNG DRAW_BALL_HORIZONTAL
	
	RET
	DRAW_BALL ENDP
CODE ENDS
END